package com.zen.entities.tenant;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "lead_social_messages")
public class LeadSocialMessage {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lead_id", nullable = false)
	private Lead lead;

	private String platform;
	private String direction;
	private String message;
	private String sentBy;

	private LocalDateTime timestamp;

	// Default constructor
	public LeadSocialMessage() {
	}

	// Builder constructor
	public LeadSocialMessage(Builder builder) {
		this.id = builder.id;
		this.lead = builder.lead;
		this.platform = builder.platform;
		this.direction = builder.direction;
		this.message = builder.message;
		this.sentBy = builder.sentBy;
		this.timestamp = builder.timestamp;
	}

	public static Builder builder() {
		return new Builder();
	}

	public static class Builder {
		private Long id;
		private Lead lead;
		private String platform;
		private String direction;
		private String message;
		private String sentBy;
		private LocalDateTime timestamp;

		public Builder id(Long id) {
			this.id = id;
			return this;
		}

		public Builder lead(Lead lead) {
			this.lead = lead;
			return this;
		}

		public Builder platform(String platform) {
			this.platform = platform;
			return this;
		}

		public Builder direction(String direction) {
			this.direction = direction;
			return this;
		}

		public Builder message(String message) {
			this.message = message;
			return this;
		}

		public Builder sentBy(String sentBy) {
			this.sentBy = sentBy;
			return this;
		}

		public Builder timestamp(LocalDateTime timestamp) {
			this.timestamp = timestamp;
			return this;
		}

		public LeadSocialMessage build() {
			return new LeadSocialMessage(this);
		}
	}

	// Getters and setters (can be generated by your IDE or Lombok)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Lead getLead() {
		return lead;
	}

	public void setLead(Lead lead) {
		this.lead = lead;
	}

	public String getPlatform() {
		return platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getDirection() {
		return direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getSentBy() {
		return sentBy;
	}

	public void setSentBy(String sentBy) {
		this.sentBy = sentBy;
	}

	public LocalDateTime getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(LocalDateTime timestamp) {
		this.timestamp = timestamp;
	}
}
