package com.zen.entities.tenant;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "lead_social_messages")
public class LeadSocialMessage {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lead_id", nullable = false)
	private Lead lead;
	
	// Compatibility field for services that use leadId directly
	@Column(name = "lead_id", insertable = false, updatable = false)
	private Long leadId;

	private String platform;
	private String direction;
	private String message;
	private String sentBy;
	private String recipient;
	private String status; // SENT, DELIVERED, READ, FAILED
	private String campaignId;
	private String messageId; // External platform message ID

	private LocalDateTime timestamp;

	// Default constructor
	public LeadSocialMessage() {
	}

	// Builder constructor
	public LeadSocialMessage(Builder builder) {
		this.id = builder.id;
		this.lead = builder.lead;
		this.platform = builder.platform;
		this.direction = builder.direction;
		this.message = builder.message;
		this.sentBy = builder.sentBy;
		this.recipient = builder.recipient;
		this.status = builder.status;
		this.campaignId = builder.campaignId;
		this.messageId = builder.messageId;
		this.timestamp = builder.timestamp;
	}

	public static Builder builder() {
		return new Builder();
	}

	public static class Builder {
		private Long id;
		private Lead lead;
		private String platform;
		private String direction;
		private String message;
		private String sentBy;
		private String recipient;
		private String status;
		private String campaignId;
		private String messageId;
		private LocalDateTime timestamp;

		public Builder id(Long id) {
			this.id = id;
			return this;
		}

		public Builder lead(Lead lead) {
			this.lead = lead;
			return this;
		}

		public Builder platform(String platform) {
			this.platform = platform;
			return this;
		}

		public Builder direction(String direction) {
			this.direction = direction;
			return this;
		}

		public Builder message(String message) {
			this.message = message;
			return this;
		}

		public Builder sentBy(String sentBy) {
			this.sentBy = sentBy;
			return this;
		}

		public Builder recipient(String recipient) {
			this.recipient = recipient;
			return this;
		}

		public Builder status(String status) {
			this.status = status;
			return this;
		}

		public Builder campaignId(String campaignId) {
			this.campaignId = campaignId;
			return this;
		}

		public Builder messageId(String messageId) {
			this.messageId = messageId;
			return this;
		}

		public Builder timestamp(LocalDateTime timestamp) {
			this.timestamp = timestamp;
			return this;
		}

		public LeadSocialMessage build() {
			return new LeadSocialMessage(this);
		}
	}

	// Getters and setters (can be generated by your IDE or Lombok)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Lead getLead() {
		return lead;
	}

	public void setLead(Lead lead) {
		this.lead = lead;
	}
	
	// Compatibility methods for leadId
	public Long getLeadId() {
		return leadId;
	}
	
	public void setLeadId(Long leadId) {
		this.leadId = leadId;
		if (leadId != null) {
			Lead lead = new Lead();
			lead.setId(leadId);
			this.lead = lead;
		}
	}

	public String getPlatform() {
		return platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getDirection() {
		return direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getSentBy() {
		return sentBy;
	}

	public void setSentBy(String sentBy) {
		this.sentBy = sentBy;
	}

	public LocalDateTime getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(LocalDateTime timestamp) {
		this.timestamp = timestamp;
	}

	public String getRecipient() {
		return recipient;
	}

	public void setRecipient(String recipient) {
		this.recipient = recipient;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCampaignId() {
		return campaignId;
	}

	public void setCampaignId(String campaignId) {
		this.campaignId = campaignId;
	}

	public String getMessageId() {
		return messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}
}
